# Generated by Django 5.2.5 on 2025-09-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_gmailcredentials_delete_gmailtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmailcredentials',
            options={'verbose_name': 'Gmail Credential', 'verbose_name_plural': 'Gmail Credentials'},
        ),
        migrations.AlterField(
            model_name='gmailcredentials',
            name='scopes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gmailcredentials',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
